server:
  port: 8080
  servlet:
    context-path: /zsh

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zsh?useUnicode=true&characterEncoding=utf-8&useSSL=true&verifyServerCertificate=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.pjxt.zsh.pojo
